# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Novara.Novara
PackageVersion: 9.0.0
Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/Novara-owner/Novara-Vault/releases/download/v9.0.0/Novara_Setup_9.0.0.exe
    InstallerSha256: 42b76b5eee2bec74fe3690d22cba9bbd8a1f3fe87561f6add7014baa417bb925
    InstallerSwitches:
      Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
      SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.10.0
